
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.1.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace TuiDui {
    using System;
    using Terminal.Gui;
    
    
    public partial class MainDialog : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme tgDefault;
        
        private Terminal.Gui.ColorScheme greyOnBlack;
        
        private Terminal.Gui.ColorScheme blueOnBlack;
        
        private Terminal.Gui.ColorScheme greenOnBlack;
        
        private Terminal.Gui.ColorScheme redOnBlack;
        
        private Terminal.Gui.ColorScheme blueOnBlackText;
        
        private Terminal.Gui.FrameView frameView;
        
        private Terminal.Gui.ListView notesListEvents;
        
        private Terminal.Gui.FrameView frameView2;
        
        private Terminal.Gui.TextView noteTextField;
        
        private Terminal.Gui.FrameView frameView4;
        
        private Terminal.Gui.Label label;
        
        private Terminal.Gui.TextView todoDateText;
        
        private Terminal.Gui.Label label2;
        
        private Terminal.Gui.TextField todoEventText;
        
        private Terminal.Gui.Button addTodoEvent;
        
        private Terminal.Gui.Button updateTodoEvent;
        
        private Terminal.Gui.FrameView frameView3;
        
        private Terminal.Gui.ListView todoListEvents;
        
        private Terminal.Gui.StatusBar statusBar;
        
        private Terminal.Gui.StatusItem f1EditMe;
        
        private Terminal.Gui.Button button1;
        
        private Terminal.Gui.MenuBar menuBar;
        
        private Terminal.Gui.MenuBarItem fileF9Menu;
        
        private Terminal.Gui.MenuItem editMeMenuItem;
        
        private void InitializeComponent() {
            this.menuBar = new Terminal.Gui.MenuBar();
            this.button1 = new Terminal.Gui.Button();
            this.statusBar = new Terminal.Gui.StatusBar();
            this.todoListEvents = new Terminal.Gui.ListView();
            this.frameView3 = new Terminal.Gui.FrameView();
            this.updateTodoEvent = new Terminal.Gui.Button();
            this.addTodoEvent = new Terminal.Gui.Button();
            this.todoEventText = new Terminal.Gui.TextField();
            this.label2 = new Terminal.Gui.Label();
            this.todoDateText = new Terminal.Gui.TextView();
            this.label = new Terminal.Gui.Label();
            this.frameView4 = new Terminal.Gui.FrameView();
            this.noteTextField = new Terminal.Gui.TextView();
            this.frameView2 = new Terminal.Gui.FrameView();
            this.notesListEvents = new Terminal.Gui.ListView();
            this.frameView = new Terminal.Gui.FrameView();
            this.tgDefault = new Terminal.Gui.ColorScheme();
            this.tgDefault.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Blue);
            this.tgDefault.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightCyan, Terminal.Gui.Color.Blue);
            this.tgDefault.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Gray);
            this.tgDefault.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Gray);
            this.tgDefault.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Brown, Terminal.Gui.Color.Blue);
            this.greyOnBlack = new Terminal.Gui.ColorScheme();
            this.greyOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.blueOnBlack = new Terminal.Gui.ColorScheme();
            this.blueOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Black);
            this.blueOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.Black);
            this.blueOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.greenOnBlack = new Terminal.Gui.ColorScheme();
            this.greenOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Black);
            this.greenOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Black);
            this.greenOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.redOnBlack = new Terminal.Gui.ColorScheme();
            this.redOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Red, Terminal.Gui.Color.Black);
            this.redOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightRed, Terminal.Gui.Color.Black);
            this.redOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Red, Terminal.Gui.Color.Brown);
            this.redOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightRed, Terminal.Gui.Color.Brown);
            this.redOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.blueOnBlackText = new Terminal.Gui.ColorScheme();
            this.blueOnBlackText.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Blue, Terminal.Gui.Color.Black);
            this.blueOnBlackText.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Blue, Terminal.Gui.Color.Black);
            this.blueOnBlackText.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Blue, Terminal.Gui.Color.Black);
            this.blueOnBlackText.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Blue, Terminal.Gui.Color.Black);
            this.blueOnBlackText.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Blue, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.ColorScheme = this.blueOnBlack;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.BorderBrush = Terminal.Gui.Color.Blue;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.frameView.Width = 25;
            this.frameView.Height = 47;
            this.frameView.X = 1;
            this.frameView.Y = 1;
            this.frameView.Visible = true;
            this.frameView.Data = "frameView";
            this.frameView.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.frameView.Border.Effect3D = false;
            this.frameView.Border.Effect3DBrush = null;
            this.frameView.Border.DrawMarginFrame = true;
            this.frameView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView.Title = "Notes";
            this.Add(this.frameView);
            this.notesListEvents.Width = 22;
            this.notesListEvents.Height = 3;
            this.notesListEvents.X = 0;
            this.notesListEvents.Y = 0;
            this.notesListEvents.Visible = true;
            this.notesListEvents.Data = "notesListEvents";
            this.notesListEvents.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.notesListEvents.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Item1",
                        "Item2",
                        "Item3"});
            this.notesListEvents.AllowsMarking = false;
            this.notesListEvents.AllowsMultipleSelection = true;
            this.frameView.Add(this.notesListEvents);
            this.frameView2.Width = 80;
            this.frameView2.Height = 46;
            this.frameView2.X = 27;
            this.frameView2.Y = 1;
            this.frameView2.Visible = true;
            this.frameView2.Data = "frameView2";
            this.frameView2.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.frameView2.Border.Effect3D = false;
            this.frameView2.Border.Effect3DBrush = null;
            this.frameView2.Border.DrawMarginFrame = true;
            this.frameView2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView2.Title = "Editor";
            this.Add(this.frameView2);
            this.noteTextField.Width = 49;
            this.noteTextField.Height = 16;
            this.noteTextField.X = 0;
            this.noteTextField.Y = 0;
            this.noteTextField.Visible = true;
            this.noteTextField.ColorScheme = this.blueOnBlackText;
            this.noteTextField.AllowsTab = true;
            this.noteTextField.AllowsReturn = true;
            this.noteTextField.WordWrap = true;
            this.noteTextField.Data = "noteTextField";
            this.noteTextField.Text = "Heya";
            this.noteTextField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView2.Add(this.noteTextField);
            this.frameView4.Width = 102;
            this.frameView4.Height = 6;
            this.frameView4.X = 108;
            this.frameView4.Y = 1;
            this.frameView4.Visible = true;
            this.frameView4.Data = "frameView4";
            this.frameView4.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.frameView4.Border.Effect3D = false;
            this.frameView4.Border.Effect3DBrush = null;
            this.frameView4.Border.DrawMarginFrame = true;
            this.frameView4.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView4.Title = "Add/Remove To-Do";
            this.Add(this.frameView4);
            this.label.Width = 7;
            this.label.Height = 1;
            this.label.X = 0;
            this.label.Y = 0;
            this.label.Visible = true;
            this.label.Data = "label";
            this.label.Text = "Date:";
            this.label.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView4.Add(this.label);
            this.todoDateText.Width = 10;
            this.todoDateText.Height = 1;
            this.todoDateText.X = 8;
            this.todoDateText.Y = 0;
            this.todoDateText.Visible = true;
            this.todoDateText.ColorScheme = this.blueOnBlackText;
            this.todoDateText.AllowsTab = false;
            this.todoDateText.AllowsReturn = false;
            this.todoDateText.WordWrap = false;
            this.todoDateText.Data = "todoDateText";
            this.todoDateText.Text = "MM/DD/YYYY";
            this.todoDateText.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView4.Add(this.todoDateText);
            this.label2.Width = 5;
            this.label2.Height = 1;
            this.label2.X = 0;
            this.label2.Y = 1;
            this.label2.Visible = true;
            this.label2.Data = "label2";
            this.label2.Text = "Event:";
            this.label2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView4.Add(this.label2);
            this.todoEventText.Width = 48;
            this.todoEventText.Height = 2;
            this.todoEventText.X = 8;
            this.todoEventText.Y = 1;
            this.todoEventText.Visible = true;
            this.todoEventText.ColorScheme = this.blueOnBlackText;
            this.todoEventText.Secret = false;
            this.todoEventText.Data = "todoEventText";
            this.todoEventText.Text = "";
            this.todoEventText.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView4.Add(this.todoEventText);
            this.addTodoEvent.Width = 9;
            this.addTodoEvent.Height = 2;
            this.addTodoEvent.X = -1;
            this.addTodoEvent.Y = 3;
            this.addTodoEvent.Visible = true;
            this.addTodoEvent.Data = "addTodoEvent";
            this.addTodoEvent.Text = "Add";
            this.addTodoEvent.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.addTodoEvent.IsDefault = false;
            this.frameView4.Add(this.addTodoEvent);
            this.updateTodoEvent.Width = 10;
            this.updateTodoEvent.Height = 1;
            this.updateTodoEvent.X = 8;
            this.updateTodoEvent.Y = 3;
            this.updateTodoEvent.Visible = true;
            this.updateTodoEvent.Data = "updateTodoEvent";
            this.updateTodoEvent.Text = "Update";
            this.updateTodoEvent.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.updateTodoEvent.IsDefault = false;
            this.frameView4.Add(this.updateTodoEvent);
            this.frameView3.Width = 102;
            this.frameView3.Height = 10;
            this.frameView3.X = 108;
            this.frameView3.Y = 7;
            this.frameView3.Visible = true;
            this.frameView3.Data = "frameView3";
            this.frameView3.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.frameView3.Border.Effect3D = false;
            this.frameView3.Border.Effect3DBrush = null;
            this.frameView3.Border.DrawMarginFrame = true;
            this.frameView3.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView3.Title = "To-Do";
            this.Add(this.frameView3);
            this.todoListEvents.Width = 39;
            this.todoListEvents.Height = 8;
            this.todoListEvents.X = 0;
            this.todoListEvents.Y = 0;
            this.todoListEvents.Visible = true;
            this.todoListEvents.Data = "todoListEvents";
            this.todoListEvents.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.todoListEvents.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Item1",
                        "Item2",
                        "Item3"});
            this.todoListEvents.AllowsMarking = false;
            this.todoListEvents.AllowsMultipleSelection = true;
            this.frameView3.Add(this.todoListEvents);
            this.statusBar.Width = Dim.Fill(0);
            this.statusBar.Height = 1;
            this.statusBar.X = 0;
            this.statusBar.Y = Pos.AnchorEnd(1);
            this.statusBar.Visible = true;
            this.statusBar.Data = "statusBar";
            this.statusBar.Text = "";
            this.statusBar.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.f1EditMe = new Terminal.Gui.StatusItem(((Terminal.Gui.Key)(1048588u)), "F1 - Edit Me", null);
            this.statusBar.Items = new Terminal.Gui.StatusItem[] {
                    this.f1EditMe};
            this.Add(this.statusBar);
            this.button1.Width = 53;
            this.button1.Height = 1;
            this.button1.X = 181;
            this.button1.Y = 48;
            this.button1.Visible = true;
            this.button1.Data = "button1";
            this.button1.Text = "Heya";
            this.button1.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.button1.IsDefault = false;
            this.Add(this.button1);
            this.menuBar.Width = Dim.Fill(0);
            this.menuBar.Height = 1;
            this.menuBar.X = 0;
            this.menuBar.Y = 0;
            this.menuBar.Visible = true;
            this.menuBar.ColorScheme = this.blueOnBlack;
            this.menuBar.Data = "menuBar";
            this.menuBar.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.fileF9Menu = new Terminal.Gui.MenuBarItem();
            this.fileF9Menu.Title = "_File (F9)";
            this.editMeMenuItem = new Terminal.Gui.MenuItem();
            this.editMeMenuItem.Title = "Edit Me";
            this.editMeMenuItem.Data = "editMeMenuItem";
            this.fileF9Menu.Children = new Terminal.Gui.MenuItem[] {
                    this.editMeMenuItem};
            this.menuBar.Menus = new Terminal.Gui.MenuBarItem[] {
                    this.fileF9Menu};
            this.Add(this.menuBar);
        }
    }
}
