
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.1.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace TuiDui {
    using System;
    using Terminal.Gui;
    
    
    public partial class MainDialog : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme tgDefault;
        
        private Terminal.Gui.ColorScheme greyOnBlack;
        
        private Terminal.Gui.ColorScheme blueOnBlack;
        
        private Terminal.Gui.ColorScheme greenOnBlack;
        
        private Terminal.Gui.ColorScheme redOnBlack;
        
        private Terminal.Gui.ColorScheme blueOnBlackText;
        
        private Terminal.Gui.FrameView noteListFrame;
        
        private Terminal.Gui.ListView noteListEvents;
        
        private Terminal.Gui.FrameView noteEntryFrame;
        
        private Terminal.Gui.TextView noteTextField;
        
        private Terminal.Gui.FrameView toDoEntry;
        
        private Terminal.Gui.Label label;
        
        private Terminal.Gui.TextView todoDateText;
        
        private Terminal.Gui.Label label2;
        
        private Terminal.Gui.TextField todoEventText;
        
        private Terminal.Gui.Button addTodoEvent;
        
        private Terminal.Gui.Button updateTodoEvent;
        
        private Terminal.Gui.FrameView toDoFrame;
        
        private Terminal.Gui.ListView todoListEvents;
        
        private Terminal.Gui.StatusBar statusBar;
        
        private Terminal.Gui.StatusItem f1EditMe;
        
        private Terminal.Gui.MenuBar menuBar;
        
        private Terminal.Gui.MenuBarItem fileMenu;
        
        private Terminal.Gui.MenuItem editMeMenuItem;
        
        private Terminal.Gui.MenuBarItem editMenu;
        
        private Terminal.Gui.MenuItem editMeMenuItem2;
        
        private Terminal.Gui.MenuBarItem helpMenu;
        
        private Terminal.Gui.MenuItem editMeMenuItem3;
        
        private void InitializeComponent() {
            this.menuBar = new Terminal.Gui.MenuBar();
            this.statusBar = new Terminal.Gui.StatusBar();
            this.todoListEvents = new Terminal.Gui.ListView();
            this.toDoFrame = new Terminal.Gui.FrameView();
            this.updateTodoEvent = new Terminal.Gui.Button();
            this.addTodoEvent = new Terminal.Gui.Button();
            this.todoEventText = new Terminal.Gui.TextField();
            this.label2 = new Terminal.Gui.Label();
            this.todoDateText = new Terminal.Gui.TextView();
            this.label = new Terminal.Gui.Label();
            this.toDoEntry = new Terminal.Gui.FrameView();
            this.noteTextField = new Terminal.Gui.TextView();
            this.noteEntryFrame = new Terminal.Gui.FrameView();
            this.noteListEvents = new Terminal.Gui.ListView();
            this.noteListFrame = new Terminal.Gui.FrameView();
            this.tgDefault = new Terminal.Gui.ColorScheme();
            this.tgDefault.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Blue);
            this.tgDefault.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightCyan, Terminal.Gui.Color.Blue);
            this.tgDefault.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Gray);
            this.tgDefault.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Gray);
            this.tgDefault.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Brown, Terminal.Gui.Color.Blue);
            this.greyOnBlack = new Terminal.Gui.ColorScheme();
            this.greyOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.blueOnBlack = new Terminal.Gui.ColorScheme();
            this.blueOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Black);
            this.blueOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.Black);
            this.blueOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.greenOnBlack = new Terminal.Gui.ColorScheme();
            this.greenOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Black);
            this.greenOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Black);
            this.greenOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.redOnBlack = new Terminal.Gui.ColorScheme();
            this.redOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Red, Terminal.Gui.Color.Black);
            this.redOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightRed, Terminal.Gui.Color.Black);
            this.redOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Red, Terminal.Gui.Color.Brown);
            this.redOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightRed, Terminal.Gui.Color.Brown);
            this.redOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.blueOnBlackText = new Terminal.Gui.ColorScheme();
            this.blueOnBlackText.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Blue, Terminal.Gui.Color.Black);
            this.blueOnBlackText.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Blue, Terminal.Gui.Color.Black);
            this.blueOnBlackText.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Blue, Terminal.Gui.Color.Black);
            this.blueOnBlackText.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Blue, Terminal.Gui.Color.Black);
            this.blueOnBlackText.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Blue, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.ColorScheme = this.blueOnBlack;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.BorderBrush = Terminal.Gui.Color.Blue;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.noteListFrame.Width = 25;
            this.noteListFrame.Height = 47;
            this.noteListFrame.X = 1;
            this.noteListFrame.Y = 1;
            this.noteListFrame.Visible = true;
            this.noteListFrame.Data = "noteListFrame";
            this.noteListFrame.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.noteListFrame.Border.Effect3D = false;
            this.noteListFrame.Border.Effect3DBrush = null;
            this.noteListFrame.Border.DrawMarginFrame = true;
            this.noteListFrame.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.noteListFrame.Title = "Notes";
            this.Add(this.noteListFrame);
            this.noteListEvents.Width = 21;
            this.noteListEvents.Height = 3;
            this.noteListEvents.X = 1;
            this.noteListEvents.Y = 0;
            this.noteListEvents.Visible = true;
            this.noteListEvents.Data = "noteListEvents";
            this.noteListEvents.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.noteListEvents.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Item1",
                        "Item2",
                        "Item3"});
            this.noteListEvents.AllowsMarking = false;
            this.noteListEvents.AllowsMultipleSelection = true;
            this.noteListFrame.Add(this.noteListEvents);
            this.noteEntryFrame.Width = 80;
            this.noteEntryFrame.Height = 46;
            this.noteEntryFrame.X = 27;
            this.noteEntryFrame.Y = 1;
            this.noteEntryFrame.Visible = true;
            this.noteEntryFrame.Data = "noteEntryFrame";
            this.noteEntryFrame.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.noteEntryFrame.Border.Effect3D = false;
            this.noteEntryFrame.Border.Effect3DBrush = null;
            this.noteEntryFrame.Border.DrawMarginFrame = true;
            this.noteEntryFrame.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.noteEntryFrame.Title = "Editor";
            this.Add(this.noteEntryFrame);
            this.noteTextField.Width = 76;
            this.noteTextField.Height = 44;
            this.noteTextField.X = 1;
            this.noteTextField.Y = 0;
            this.noteTextField.Visible = true;
            this.noteTextField.ColorScheme = this.blueOnBlackText;
            this.noteTextField.AllowsTab = false;
            this.noteTextField.AllowsReturn = true;
            this.noteTextField.WordWrap = true;
            this.noteTextField.Data = "noteTextField";
            this.noteTextField.Text = "";
            this.noteTextField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.noteEntryFrame.Add(this.noteTextField);
            this.toDoEntry.Width = 102;
            this.toDoEntry.Height = 6;
            this.toDoEntry.X = 108;
            this.toDoEntry.Y = 1;
            this.toDoEntry.Visible = true;
            this.toDoEntry.Data = "toDoEntry";
            this.toDoEntry.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.toDoEntry.Border.Effect3D = false;
            this.toDoEntry.Border.Effect3DBrush = null;
            this.toDoEntry.Border.DrawMarginFrame = true;
            this.toDoEntry.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.toDoEntry.Title = "Add/Remove To-Do";
            this.Add(this.toDoEntry);
            this.label.Width = 7;
            this.label.Height = 1;
            this.label.X = 1;
            this.label.Y = 0;
            this.label.Visible = true;
            this.label.Data = "label";
            this.label.Text = "Date:";
            this.label.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.toDoEntry.Add(this.label);
            this.todoDateText.Width = 10;
            this.todoDateText.Height = 1;
            this.todoDateText.X = 9;
            this.todoDateText.Y = 0;
            this.todoDateText.Visible = true;
            this.todoDateText.ColorScheme = this.blueOnBlackText;
            this.todoDateText.AllowsTab = false;
            this.todoDateText.AllowsReturn = false;
            this.todoDateText.WordWrap = false;
            this.todoDateText.Data = "todoDateText";
            this.todoDateText.Text = "MM/DD/YYYY";
            this.todoDateText.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.toDoEntry.Add(this.todoDateText);
            this.label2.Width = 5;
            this.label2.Height = 1;
            this.label2.X = 1;
            this.label2.Y = 1;
            this.label2.Visible = true;
            this.label2.Data = "label2";
            this.label2.Text = "Event:";
            this.label2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.toDoEntry.Add(this.label2);
            this.todoEventText.Width = 83;
            this.todoEventText.Height = 1;
            this.todoEventText.X = 9;
            this.todoEventText.Y = 1;
            this.todoEventText.Visible = true;
            this.todoEventText.ColorScheme = this.blueOnBlackText;
            this.todoEventText.Secret = false;
            this.todoEventText.Data = "todoEventText";
            this.todoEventText.Text = "";
            this.todoEventText.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.toDoEntry.Add(this.todoEventText);
            this.addTodoEvent.Width = 9;
            this.addTodoEvent.Height = 2;
            this.addTodoEvent.X = 0;
            this.addTodoEvent.Y = 3;
            this.addTodoEvent.Visible = true;
            this.addTodoEvent.Data = "addTodoEvent";
            this.addTodoEvent.Text = "Add";
            this.addTodoEvent.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.addTodoEvent.IsDefault = false;
            this.toDoEntry.Add(this.addTodoEvent);
            this.updateTodoEvent.Width = 10;
            this.updateTodoEvent.Height = 1;
            this.updateTodoEvent.X = 9;
            this.updateTodoEvent.Y = 3;
            this.updateTodoEvent.Visible = true;
            this.updateTodoEvent.Data = "updateTodoEvent";
            this.updateTodoEvent.Text = "Update";
            this.updateTodoEvent.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.updateTodoEvent.IsDefault = false;
            this.toDoEntry.Add(this.updateTodoEvent);
            this.toDoFrame.Width = 102;
            this.toDoFrame.Height = 13;
            this.toDoFrame.X = 108;
            this.toDoFrame.Y = 7;
            this.toDoFrame.Visible = true;
            this.toDoFrame.Data = "toDoFrame";
            this.toDoFrame.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.toDoFrame.Border.Effect3D = false;
            this.toDoFrame.Border.Effect3DBrush = null;
            this.toDoFrame.Border.DrawMarginFrame = true;
            this.toDoFrame.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.toDoFrame.Title = "To-Do List";
            this.Add(this.toDoFrame);
            this.todoListEvents.Width = 98;
            this.todoListEvents.Height = 11;
            this.todoListEvents.X = 1;
            this.todoListEvents.Y = 0;
            this.todoListEvents.Visible = true;
            this.todoListEvents.Data = "todoListEvents";
            this.todoListEvents.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.todoListEvents.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Item1",
                        "Item2",
                        "Item3"});
            this.todoListEvents.AllowsMarking = false;
            this.todoListEvents.AllowsMultipleSelection = true;
            this.toDoFrame.Add(this.todoListEvents);
            this.statusBar.Width = Dim.Fill(0);
            this.statusBar.Height = 1;
            this.statusBar.X = 0;
            this.statusBar.Y = Pos.AnchorEnd(1);
            this.statusBar.Visible = true;
            this.statusBar.Data = "statusBar";
            this.statusBar.Text = "";
            this.statusBar.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.f1EditMe = new Terminal.Gui.StatusItem(((Terminal.Gui.Key)(1048588u)), "F1 - Edit Me", null);
            this.statusBar.Items = new Terminal.Gui.StatusItem[] {
                    this.f1EditMe};
            this.Add(this.statusBar);
            this.menuBar.Width = Dim.Fill(0);
            this.menuBar.Height = 1;
            this.menuBar.X = 0;
            this.menuBar.Y = 0;
            this.menuBar.Visible = true;
            this.menuBar.ColorScheme = this.blueOnBlack;
            this.menuBar.Data = "menuBar";
            this.menuBar.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.fileMenu = new Terminal.Gui.MenuBarItem();
            this.fileMenu.Title = "_File";
            this.editMeMenuItem = new Terminal.Gui.MenuItem();
            this.editMeMenuItem.Title = "Edit Me";
            this.editMeMenuItem.Data = "editMeMenuItem";
            this.fileMenu.Children = new Terminal.Gui.MenuItem[] {
                    this.editMeMenuItem};
            this.editMenu = new Terminal.Gui.MenuBarItem();
            this.editMenu.Title = "_Edit";
            this.editMeMenuItem2 = new Terminal.Gui.MenuItem();
            this.editMeMenuItem2.Title = "Edit Me";
            this.editMeMenuItem2.Data = "editMeMenuItem2";
            this.editMenu.Children = new Terminal.Gui.MenuItem[] {
                    this.editMeMenuItem2};
            this.helpMenu = new Terminal.Gui.MenuBarItem();
            this.helpMenu.Title = "_Help";
            this.editMeMenuItem3 = new Terminal.Gui.MenuItem();
            this.editMeMenuItem3.Title = "Edit Me";
            this.editMeMenuItem3.Data = "editMeMenuItem3";
            this.helpMenu.Children = new Terminal.Gui.MenuItem[] {
                    this.editMeMenuItem3};
            this.menuBar.Menus = new Terminal.Gui.MenuBarItem[] {
                    this.fileMenu,
                    this.editMenu,
                    this.helpMenu};
            this.Add(this.menuBar);
        }
    }
}
